on:
  push:
    branches: [master]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker run -v $(pwd):/test ruby:alpine sh -c "cd /test && apk add build-base chromium && bundle install && ruby test.rb"
